// src/lib/presets.ts
"use client";
import {
  Github,
  Facebook,
  Instagram,
  Twitter,
  Linkedin,
  Youtube,
  Dribbble,
  Code2,
  Mail,
  Globe,
  BookOpen,
  GraduationCap,
  Codepen,
  MessageSquare,
  Twitch,
  Gamepad2,
  Layers,
} from "lucide-react";

export type Preset = {
  key: string;
  label: string;
  baseUrl: string;
  placeholderUsername?: string;
  category: "Social" | "Dev" | "Education" | "Other";
  icon: React.ElementType;
  usernameRegex?: string;
};

export const PRESETS: Preset[] = [
  {
    key: "github",
    label: "GitHub",
    baseUrl: "https://github.com/",
    placeholderUsername: "maremon7415",
    category: "Dev",
    icon: Github,
    usernameRegex: "^[A-Za-z0-9-]{1,39}$",
  },
  {
    key: "facebook",
    label: "Facebook",
    baseUrl: "https://facebook.com/",
    placeholderUsername: "maremon15",
    category: "Social",
    icon: Facebook,
    usernameRegex: "^[A-Za-z0-9.]{1,50}$",
  },
  {
    key: "instagram",
    label: "Instagram",
    baseUrl: "https://instagram.com/",
    placeholderUsername: "maremon",
    category: "Social",
    icon: Instagram,
    usernameRegex: "^[A-Za-z0-9._]{1,30}$",
  },
  {
    key: "x",
    label: "X (Twitter)",
    baseUrl: "https://x.com/",
    placeholderUsername: "maremon",
    category: "Social",
    icon: Twitter,
    usernameRegex: "^[A-Za-z0-9_]{1,15}$",
  },
  {
    key: "linkedin",
    label: "LinkedIn",
    baseUrl: "https://linkedin.com/in/",
    placeholderUsername: "maremon",
    category: "Social",
    icon: Linkedin,
    usernameRegex: "^[A-Za-z0-9-]{3,100}$",
  },
  {
    key: "youtube",
    label: "YouTube",
    baseUrl: "https://youtube.com/",
    placeholderUsername: "@maremon",
    category: "Social",
    icon: Youtube,
    usernameRegex: "^@[A-Za-z0-9._-]{3,30}$",
  },
  {
    key: "dribbble",
    label: "Dribbble",
    baseUrl: "https://dribbble.com/",
    placeholderUsername: "maremon",
    category: "Dev",
    icon: Dribbble,
    usernameRegex: "^[A-Za-z0-9_-]{1,30}$",
  },
  {
    key: "twitch",
    label: "Twitch",
    baseUrl: "https://twitch.tv/",
    placeholderUsername: "maremon",
    category: "Social",
    icon: Twitch,
    usernameRegex: "^[A-Za-z0-9_]{4,25}$",
  },
  {
    key: "leetcode",
    label: "LeetCode",
    baseUrl: "https://leetcode.com/",
    placeholderUsername: "maremon",
    category: "Dev",
    icon: Code2,
    usernameRegex: "^[A-Za-z0-9_\\-]+$",
  },
  {
    key: "kaggle",
    label: "Kaggle",
    baseUrl: "https://kaggle.com/",
    placeholderUsername: "maremon",
    category: "Dev",
    icon: Layers,
    usernameRegex: "^[A-Za-z0-9_]+$",
  },
  {
    key: "stackoverflow",
    label: "Stack Overflow",
    baseUrl: "https://stackoverflow.com/users/",
    placeholderUsername: "1234567/maremon",
    category: "Dev",
    icon: MessageSquare,
    usernameRegex: "^[0-9]+/[A-Za-z0-9_-]+$",
  },
  {
    key: "codepen",
    label: "CodePen",
    baseUrl: "https://codepen.io/",
    placeholderUsername: "maremon",
    category: "Dev",
    icon: Codepen,
    usernameRegex: "^[A-Za-z0-9_-]+$",
  },
  {
    key: "coursera",
    label: "Coursera",
    baseUrl: "https://coursera.org/user/",
    placeholderUsername: "maremon",
    category: "Education",
    icon: BookOpen,
    usernameRegex: "^[A-Za-z0-9_-]+$",
  },
  {
    key: "udemy",
    label: "Udemy",
    baseUrl: "https://udemy.com/user/",
    placeholderUsername: "maremon",
    category: "Education",
    icon: GraduationCap,
    usernameRegex: "^[A-Za-z0-9_-]+$",
  },
  {
    key: "portfolio",
    label: "Portfolio",
    baseUrl: "https://",
    placeholderUsername: "maremon.dev",
    category: "Other",
    icon: Globe,
    usernameRegex: "^[A-Za-z0-9.-]+$",
  },
  {
    key: "email",
    label: "Email",
    baseUrl: "mailto:",
    placeholderUsername: "emon747415@gmail.com",
    category: "Other",
    icon: Mail,
    usernameRegex: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$",
  },
  {
    key: "medium",
    label: "Medium",
    baseUrl: "https://medium.com/@",
    placeholderUsername: "maremon",
    category: "Social",
    icon: BookOpen, // reuse BookOpen as medium icon alternative
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "discord",
    label: "Discord",
    baseUrl: "https://discord.com/users/",
    placeholderUsername: "123456789012345678",
    category: "Social",
    icon: MessageSquare, // no direct discord icon, reuse MessageSquare
    usernameRegex: "^[0-9]{17,20}$",
  },
  {
    key: "bitbucket",
    label: "Bitbucket",
    baseUrl: "https://bitbucket.org/",
    placeholderUsername: "maremon",
    category: "Dev",
    icon: Github, // no bitbucket icon, reuse Github
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "gitlab",
    label: "GitLab",
    baseUrl: "https://gitlab.com/",
    placeholderUsername: "maremon",
    category: "Dev",
    icon: Github, // no gitlab icon, reuse Github
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "edx",
    label: "edX",
    baseUrl: "https://www.edx.org/user/",
    placeholderUsername: "maremon",
    category: "Education",
    icon: GraduationCap,
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "khanacademy",
    label: "Khan Academy",
    baseUrl: "https://www.khanacademy.org/profile/",
    placeholderUsername: "maremon",
    category: "Education",
    icon: GraduationCap,
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "tumblr",
    label: "Tumblr",
    baseUrl: "https://",
    placeholderUsername: "maremon",
    category: "Social",
    icon: Instagram, // reuse Instagram icon for Tumblr
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "snapchat",
    label: "Snapchat",
    baseUrl: "https://snapchat.com/add/",
    placeholderUsername: "maremon",
    category: "Social",
    icon: Instagram, // no direct icon, reuse Instagram
    usernameRegex: "^[A-Za-z0-9_-]{1,30}$",
  },
  {
    key: "patreon",
    label: "Patreon",
    baseUrl: "https://patreon.com/",
    placeholderUsername: "maremon",
    category: "Other",
    icon: Layers,
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "paypal",
    label: "PayPal",
    baseUrl: "https://paypal.me/",
    placeholderUsername: "maremon",
    category: "Other",
    icon: Globe,
    usernameRegex: "^[A-Za-z0-9_-]{1,50}$",
  },
  {
    key: "telegram",
    label: "Telegram",
    baseUrl: "https://t.me/",
    placeholderUsername: "maremon",
    category: "Social",
    icon: MessageSquare,
    usernameRegex: "^[A-Za-z0-9_]{5,32}$",
  },
];
